name: Release on Merge to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Extract version from setup.py
        id: get_version
        run: |
          VERSION=$(python -c "import re; f=open('setup.py').read(); print(re.search(r\"version=['\\\"]([^'\\\"]*)['\\\"]\", f).group(1))")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Bump version and create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          name: ${{ steps.get_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
